apiVersion: v1
kind: Secret
metadata: 
  name: mongo-secret
type: Opaque 
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=

#If your MongoDB root username is admin and the password is password, you can encode them using the base64 command:

# echo -n 'admin' | base64
# # Output: YWRtaW4=

# echo -n 'password' | base64
# # Output: cGFzc3dvcmQ=

# To decode the base64-encoded string cGFzc3dvcmQ= back to its original value:

# echo 'cGFzc3dvcmQ=' | base64 -d
# # Output: password